### ISSUE TITLE
Recomendaciones de mejora

### ISSUE THREAD

**Issue by gaposx** [miluskagonzalez/lim-2018-05-bc-core-am-datadashboard#10]
**GENERAL**
* Ojo! El ordenamiento de forma ASC y DESC para las características numéricas (completitud, puntuación) se encuentra implementado al revés.

**HTML**
* No olvides validar tu HTML, revisa [esta URL](https://validator.w3.org/nu/?doc=https%3A%2F%2Fmiluskagonzalez.github.io%2Flim-2018-05-bc-core-am-datadashboard%2Fsrc%2F) para que observes tus errores y advertencias.

**JS**
* No olvides eliminar tus invocaciones al _console.log_.
* Tener cuidado con el uso de variables/funciones que nunca fueron declaradas (21:21 `main.js`: `processCohortData`).
* Revisar que no se usen `;` no requeridos (68:4 `main.js`)

Muy buen trabajo!

**Comment by miluskagonzalez** [comment]
Muchas gracias por el feedback, @gaposx!
Tengo una duda respecto a esta parte:
> JS
> - Tener cuidado con el uso de variables/funciones que nunca fueron declaradas (21:21 main.js: processCohortData).

La función processCohortData está definida de manera global en el archivo data.js (línea 125). ¿Hay alguna forma de llamar a esta función desde el archivo main.js sin que se presente como un error?
